service: skill-alexa

package:
  individually: true
  exclude:
    - awscliv2.zip
    - terraform/**
    - aws/**

frameworkVersion: '3'

custom:
  lamdbaAlexa: lmb-${self:provider.stage}-${self:service}-helloword-01
  alexaSkill: amzn1.ask.skill.de0d6d2b-f5ec-482e-8216-2acbe008a41a
  esbuild:
    bundle: true
    minify: true
    metafile: false
    exclude:
    - 'aws-sdk'
    target: 'node14'
    platform: 'node'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  stage: dev
  
functions:
  helloWord:
    handler: src/infraestructure/handlers/hello-handler.getHello
    name: ${self:custom.lamdbaAlexa}
    description: this function is for hello test
    events:
      - alexaSkill: ${self:custom.alexaSkill}

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-import-apigateway
  - serverless-step-functions
  